using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LobbyFileParserTest
{
    public static class HeroLists
    {
        public static List<string> Heroes = new List<string>()
        {
            "Abathur",
            "Alarak",
            "Alexstrasza",
            "Ana",
            "Anub'arak",
            "Artanis",
            "Arthas",
            "Auriel",
            "Azmodan",
            "Blaze",
            "Brightwing",
            "Butcher",
            "Cassia",
            "Chen",
            "Cho",
            "Chromie",
            "Dehaka",
            "Diablo",
            "D.Va",
            "E.T.C.",
            "Falstad",
            "Gall",
            "Garrosh",
            "Hanzo",
            "Gazlowe",
            "Genji",
            "Greymane",
            "Gul'dan",
            "Illidan",
            "Jaina",
            "Johanna",
            "Junkrat",
            "Kael'thas",
            "Kel'Thuzad",
            "Kerrigan",
            "Kharazim",
            "Leoric",
            "Li Li",
            "Li-Ming",
            "Lost Vikings",
            "Lúcio",
            "Lt. Morales",
            "Lunara",
            "Malfurion",
            "Malthael",
            "Medivh",
            "Muradin",
            "Murky",
            "Nazeebo",
            "Nova",
            "Probius",
            "Ragnaros",
            "Raynor",
            "Rehgar",
            "Rexxar",
            "Samuro",
            "Sgt. Hammer",
            "Sonya",
            "Stitches",
            "Stukov",
            "Sylvanas",
            "Tassadar",
            "Thrall",
            "Tracer",
            "Tychus",
            "Tyrael",
            "Tyrande",
            "Uther",
            "Valeera",
            "Valla",
            "Varian",
            "Xul",
            "Zagara",
            "Zarya",
            "Zeratul",
            "Zul'jin",
        };
    }
}
